### ISSUE TITLE
Builtin Filters

### ISSUE THREAD

**Issue by dfee** [kblomqvist/yasha#20]
It'd be helpful if there were some builtin filters that were common. For instance, here is my extension file:

```python
import os

def filter_env(value, default=None):
    return os.environ.get(value, default)
```

For use in a template like:
```yaml
--
components:
  sqlalchemy:
    url: {{ 'POSTGRES_URL' | env }}
```

Would you consider adding this functionality?

**Comment by kblomqvist** [comment]
I like the idea of having this kind convenience filters. Do you have some other examples in mind?

**Comment by dfee** [comment]
How about these three filters, which would provide unlimited flexibility:

```python
import subprocess

def filter_subprocess(args, stdout=True, stderr=True, shell=True, check=True):
    kwargs = dict(
        args=args,
        stdout=subprocess.PIPE if stdout else None,
        stderr=subprocess.PIPE if stderr else None,
        shell=shell,
        check=check,
    )
    return subprocess.run(**kwargs)

def filter_stdout(cp):
    assert isinstance(cp, subprocess.CompletedProcess)
    return cp.stdout.decode() if cp.stdout else None

def filter_stderr(cp):
    assert isinstance(cp, subprocess.CompletedProcess)
    return cp.stderr.decode() if cp.stderr else None
```

for usage:

```yaml
os:
    type: {{ "lsb_release -a | grep Distributor | awk '{print $3}'" | subprocess | stdout }}
    version: {{ 'cat /etc/debian_version' | subprocess | stdout }}
```

producing:
```yaml
os:
    type: Debian
    version: 9.1
```

```

**Comment by kblomqvist** [comment]
Nice. I will add.

Do you mind if I make `env` filter to work like this:

```python
def filter_env(default, key):
    return os.environ.get(key, default)
```

```yaml
components:
  sqlalchemy:
    url: {{ 'postgresql://default' | env('POSTGRES_URL') }}
```
